Stem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('jamoa/', include('teachers.urls', namespace='teachers')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("elonlar/", ReportsView.as_view(), name="report"),
    path("elon/<pk>", report_detail, name="report_detail"),
    path("yangiliklar/", NewsView.as_view(), name="news"),
    path("yangilik/<pk>", news_detail, name="news_detail"),
    path("comment/", comment, name="comment"),
]

teachers/urls.py
from django.urls import path
from .views import *

app_name = 'teachers'

urlpatterns = [
    path("", TeamView.as_view(), name="team"),
    path("boglanish/", contact, name="contact"),
    path("boglan/", get_contact, name="con")
]

main/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    title = models.CharField("Nomi", max_length=150)
    slug = models.SlugField("*")
    
    def __str__(self):
        return self.title


class Gellary(models.Model):
    title = models.CharField("izoh", max_length=150, blank=True)
    image = models.ImageField("rasm", upload_to='gellary/')

    def __str__(self):
        return self.image.url


class News(models.Model):
    author = models.ForeignKey("teachers.Teacher", related_name="news", on_delete=models.CASCADE)
    title = models.CharField("Sarlavha", max_length=350)
    image = models.ImageField("Rasmi", upload_to='news_images/')
    video = models.CharField("Video", max_length=60, blank=True)
    category = models.ForeignKey("main.Category", related_name="news", on_delete=models.CASCADE)
    gellary = models.ManyToManyField("main.Gellary", related_name="gnews", blank=True)
    body = models.TextField("Matni")
    date = models.DateField("sanasi", auto_now_add=True)

    def __str__(self):
        return self.title


class Reports(models.Model):
    title = models.CharField("Sarlavha", max_length=550)
    category = models.ForeignKey("main.Category", related_name="Reports", on_delete=models.CASCADE)
    image = models.ImageField("Rasmi", upload_to='report_images')
    description = models.TextField("Qoshimcha", blank=True)
    date = models.DateField("sanasi", auto_now_add=True)

    def __str__(self):
        return self.title


class Comments(models.Model):
    news = models.ForeignKey("main.News", related_name="comments", on_delete=models.CASCADE)
    name = models.CharField("Ismi", max_length=50)
    surname = models.CharField("Familiya", max_length=50)
    message = models.TextField("Message")
    date = models.DateTimeField("Date", auto_now_add=True)

    def create(self, news, name, surname, message):
        new = Comments.objects.create(
            news=news,
            name=name,
            surname=surname,
            message=message
        )
        new.save()


class Contact(models.Model):
    name = models.CharField("name", max_length=50)
    surname = models.CharField("surname", max_length=50)
    tel_number = models.CharField("tel_number", max_length=50)

    def __str__(self):
        return self.name

teachers/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

class Teacher(models.Model):
    user = models.OneToOneField(User, related_name="teacher", on_delete=models.CASCADE)
    avatar = models.ImageField("profil rasmi", upload_to='profile_images/', null=True, blank=True)
    class_name = models.CharField("sinfi", max_length=50, blank=True)
    info = models.TextField("Ma'lumot", blank=True)
    image = models.ImageField("Rasmi", upload_to='teacher_images/', null=True, blank=True)

    def __str__(self):
        return str(self.user.username)

@receiver(post_save, sender=User)
def user_created(sender, instance, created, *args, **kargs):
    if created:
        Teacher.objects.create(user=instance)
    else:
        pass


class BrithDays(models.Model):
    name = models.CharField("Ismi", max_length=150)
    day = models.DateField("Tugilgan kuni")
    image = models.ImageField("Rasmi", upload_to="birday_user/", blank=True)

    def __str__(self):
        return self.name


class Contact(models.Model):
    name = models.CharField("Ismi", max_length=50)
    surname = models.CharField("Familiyasi", max_length=50)
    tel_number = models.PositiveIntegerField("telfon")

    def __str__(self):
        return f"{self.name}, {self.surname}"

teachers/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Teacher

main/views.py
from django.http.response import JsonResponse
from django.shortcuts import render
from django.views import View
from .models import *
from .froms import *

# Create your views here.

class HomeView(View):
    def get(self, request):
        last_news = News.objects.all().order_by('-id')
        random_news = News.objects.all().order_by('?')
        last = News.objects.last()
        reports = Reports.objects.all().order_by('-id')
        context = {
            'last_news':last_news[:4],
            'random_news':random_news[:4],
            'last':last,
            'reports':reports
        }
        return render(request,'index.html', context)


class ReportsView(View):
    def get(self, request):
        reports = Reports.objects.all().order_by('-id')
        context = {
            'reports':reports,
        }
        return render(request, 'classic.html', context)


class NewsView(View):
    def get(self, request):
        news = News.objects.all()
        context = {
            'news':news,
        }
        return render(request, 'news.html', context)


def news_detail(request, pk):
    news = News.objects.get(pk=pk)
    comments = Comments.objects.filter(news=news).order_by('-id')
    context = {
        'news':news,
        'comments':comments
    }
    return render(request,'blog-single.html', context)

def comment(request):
    news_id = request.GET.get('id')
    news = News.objects.get(id=news_id)

    comment = request.GET.get('comment')
    name = request.GET.get('name')
    surname = request.GET.get('surname')
    if comment and name and surname:
        new = Comments.objects.create(
            news=news,
            name=name,
            surname=surname,
            message=comment
        )
        new.save()
        print(new.date.date())
        json = {
            'name':name,
            'surname':surname,
            'comment':comment,
            'date':'hozir',
            'status':'ERROR'
            }
    else:
        json = {'status':'ERROR'}
    return JsonResponse(json)


def report_detail(request, pk):
    repo = Reports.objects.get(pk=pk)
    context = {
        'repo':repo
    }
    return render(request, 'repo-single.html', context)

teachers/views.py
from django.shortcuts import render
from django.http.response import JsonResponse
from django.views import View
from .models import *
# Create your views here.


class TeamView(View):
    def get(self, request):
        teachers = Teacher.objects.all()
        data = {
            'teachers':teachers,
        }
        return render(request, 'team.html', data)



def brithday_view(request):
    days = BrithDays.objects.all()
    context = {
        'days':days
    }
    return context

def contact(request):
    return render(request, 'contact.html')

def get_contact(request):
    name = request.GET.get('name')
    surname = request.GET.get('surname')
    telnum = request.GET.get('phone')
    if name and surname and telnum:
        Contact.objects.create(
            name=name,
            surname=surname,
            tel_number=telnum
        )
        return JsonResponse({'status':'OK'})
    else:
        return JsonResponse({'status':'ERROR'})

templates/blog-single.html
{% extends 'sitebar.html' %}
{% load static %}

{% block sitebar %}


	<!-- section main content -->
	<section class="main-content mt-3">
		<div class="container-xl">

            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">Bosh sahifa</a></li>
                    <li class="breadcrumb-item"><a href="/yangiliklar/">Yangiliklar</a></li>
                </ol>
            </nav>

			<div class="row gy-4">

				<div class="col-lg-8">
					<!-- post single -->
                    <div class="post post-single">
						<!-- post header -->
						<div class="post-header">
							<h1 class="title mt-0 mb-3">{{news.title}}</h1><li class="list-inline-item">{{news.date}}</li>
							<ul class="meta list-inline mb-0">
								<li class="list-inline-item"><a href="#"><img src="{{news.author.avatar.url}}" class="avatar" alt="author"/>{{news.author.user.first_name|truncatechars:2}} {{news.author.user.last_name}}</a></li>
								<li class="list-inline-item"><a href="#">{{news.category}}</a></li>
								<li class="list-inline-item"><i class="icon-bubble"></i> ({{comments.all.count}})</li>
							</ul>
						</div>
						<!-- featured image -->
						
						{% if news.video %}
						<iframe width="100%" height="415" src="https://www.youtube.com/embed/{{news.video}}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
						{% else %}
						<div class="featured-image">
							<img src="{{news.image.url}}" alt="post-title" />
						</div>
						{% endif %}
						<!-- post content -->
						<div class="post-content clearfix">
							<p>{{news.body}}</p>

							<figure class="figure">
								<figcaption class="figure-caption text-center">Qo'shimcha rasmlar:</figcaption>
							</figure>

							<div class="row">
								{% for gel in news.gellary.all %}
								<div class="col-md-4">
									<img src="{{gel.image.url}}" class="rounded alignleft" alt="...">
								</div>
								{% endfor %}
							</div>
								
						</div>
						<!-- post bottom section -->
						<div class="post-bottom">
							<div class="row d-flex align-items-center">
								<div class="col-md-6 col-12 text-center text-md-start">
									<!-- tags -->
									<a href="#" class="tag">#Trending</a>
								</div>
								<div class="col-md-6 col-12">
									<!-- social icons -->
									<ul class="social-icons list-unstyled list-inline mb-0 float-md-end">
										<li class="list-inline-item"><a href="#"><i class="fab fa-telegram-plane"></i></a></li>
										<li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
										<li class="list-inline-item"><a href="#"><i class="fab fa-youtube"></i></a></li>
									</ul>
								</div>
							</div>
						</div>

                    </div>

					<div class="spacer" data-height="50"></div>

					<div class="about-author padding-30 rounded">
						<div class="thumb">
							<img src="{{news.author.avatar.url}}" alt="Katen Doe" />
						</div>
						<div class="details">
							<h4 class="name"><a href="#">{{news.author.user.first_name}} {{news.author.user.last_name}}</a></h4>
							<p>{{news.author.info}}</p>
							<!-- social icons -->
							<ul class="social-icons list-unstyled list-inline mb-0">
								<li class="list-inline-item"><a href="#"><i class="fab fa-telegram-plane"></i></a></li>
								<li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
								<li class="list-inline-item"><a href="#"><i class="fab fa-youtube"></i></a></li>
							</ul>
						</div>
					</div>

					<div class="spacer" data-height="50"></div>

					<!-- section header -->
					<div class="section-header">
						<h3 class="section-title">Fikrlar ({{comments.all.count}})</h3>
						<img src="/static/images/wave.svg" class="wave" alt="wave" />
						
					</div>
					<!-- post comments -->
					<div class="comments bordered padding-30 rounded">

						<ul class="comments commments">
							<!-- comment item -->
							
							{% for com in comments %}
							<li class="comment rounded">
								<div class="thumb">
									<img src="/static/images/other/comment-1.png" alt="John Doe" />
								</div>
								<div class="details">
									<h4 class="name"><a href="#">{{com.name}} {{com.surname}}</a></h4>
									<span class="date">{{com.date}}</span>
									<p>{{com.message}}</p>
								</div>
							</li>
							{% endfor %}
								
							
						</ul>
					</div>

					<div class="spacer" data-height="50"></div>

					<!-- section header -->
					<div class="section-header">
						<h3 class="section-title">Fikr qoldirish</h3>
						<img src="/static/images/wave.svg" class="wave" alt="wave" />
						<div class="messages_pro"></div>
					</div>
					<!-- comment form -->
					<div class="comment-form rounded bordered padding-30">

						<form id="comment-form" class="comment-form" method="POST">
							<div class="messages"></div>
							
							<div class="row">
								<div style="display: none;" class="news_id" data-id="{{news.id}}"></div>

								<div class="column col-md-12">
									<!-- Comment textarea -->
									<div class="form-group">
										<textarea class="form-control com_body"  name="fikr" rows="4" placeholder="Fikringiz..." required></textarea>
									</div>
								</div>

								<div class="column col-md-6">
									<!-- Name input -->
									<div class="form-group">
										<input type="text"  name="name" class="form-control com_name" placeholder="Ismingiz" required>
									</div>
								</div>

								<div class="column col-md-6">
									<!-- SurName input -->
									<div class="form-group">
										<input type="text"  name="surname" class="form-control com_surname" placeholder="Familiyangiz" required>
									</div>
								</div>
						
							</div>
	
							<button type="button" class="btn btn-default com_submit">Tasdiqlash</button><!-- Submit Button -->
	
						</form>
					</div>
                </div>


	
	{% endblock sitebar %}
	

templates/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>Katen - Minimal Blog & Magazine HTML Theme</title>
	<meta name="description" content="Katen - Minimal Blog & Magazine HTML Theme">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link rel="shortcut icon" type="image/x-icon" href="/static/images/stem.jpg">

	<!-- STYLES -->
	<link rel="stylesheet" href="/static/css/bootstrap.min.css" type="text/css" media="all">
	<link rel="stylesheet" href="/static/css/all.min.css" type="text/css" media="all">
	<link rel="stylesheet" href="/static/css/slick.css" type="text/css" media="all">
	<link rel="stylesheet" href="/static/css/simple-line-icons.css" type="text/css" media="all">
	<link rel="stylesheet" href="/static/css/style.css" type="text/css" media="all">

	<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

<!-- preloader -->
<div id="preloader">
	<div class="book">
		<div class="inner">
			<div class="left"></div>
			<div class="middle"></div>
			<div class="right"></div>
		</div>
		<ul>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
</div>

<!-- site wrapper -->
<div class="site-wrapper">

	<!-- header -->
	<header class="header-default">
		<nav class="navbar navbar-expand-lg">
			<div class="container-xl">
				<!-- site logo -->
				<a class="navbar-brand" href="{% url 'main:home' %}"><img src="/static/images/stem.jpg" alt="logo" width="55"/></a> 

				<div class="collapse navbar-collapse">
					<!-- menus -->
					<ul class="navbar-nav mr-auto">
						<li class="nav-item active">
							<a class="nav-link" href="{% url 'main:home' %}">Bosh sahifa</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'main:report' %}">E'lonlar</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'main:news' %}">Yangiliklar</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'teachers:team' %}">Jamoamiz</a>
						</li>
						<li class="nav-item active">
							<a class="nav-link" href="/jamoa/boglanish">Bog'lanish</a>
						</li>
					</ul>
				</div>

				<!-- header right section -->
				<div class="header-right">
					<!-- social icons -->
					<ul class="social-icons list-unstyled list-inline mb-0">
						<li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
						<li class="list-inline-item"><a href="#"><i class="fab fa-telegram"></i></a></li>
						<li class="list-inline-item"><a href="#"><i class="fab fa-youtube"></i></a></li>
					</ul>
					<!-- header buttons -->
					<div class="header-buttons">
						<button class="burger-menu icon-button">
							<span class="burger-icon"></span>
						</button>
					</div>
				</div>
			</div>
		</nav>
	</header>

    <!-- page header -->
    <section class="page-header">
        <div class="container-xl">
            <div class="text-center">
                <h1 class="mt-0 mb-2">Bog'lanish</h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb justify-content-center mb-0">
                        <li class="breadcrumb-item"><a href="#">Bosh sahifa</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Bog'lanish</li>
                    </ol>
                </nav>
            </div>
        </div>
    </section>

	<!-- section main content -->
	<section class="main-content">
		<div class="container-xl">

			<div class="row">
						
                <div class="col-md-4">
                    <!-- contact info item -->
                    <div class="contact-item bordered rounded d-flex align-items-center">
                        <span class="icon icon-phone"></span>
                        <div class="details">
                            <h3 class="mb-0 mt-0">Telefon</h3>
                            <p class="mb-0">+1-202-555-0135</p>
                        </div>
                    </div>
                    <div class="spacer d-md-none d-lg-none" data-height="30"></div>
                </div>

                <div class="col-md-4">
                    <!-- contact info item -->
                    <div class="contact-item bordered rounded d-flex align-items-center">
                        <span class="icon icon-envelope-open"></span>
                        <div class="details">
                            <h3 class="mb-0 mt-0">E-Mail</h3>
                            <p class="mb-0">hello@example.com</p>
                        </div>
                    </div>
                    <div class="spacer d-md-none d-lg-none" data-height="30"></div>
                </div>

                <div class="col-md-4">
                    <!-- contact info item -->
                    <div class="contact-item bordered rounded d-flex align-items-center">
                        <span class="icon icon-map"></span>
                        <div class="details">
							<a href="https://www.google.com/maps/place/STEM+School+Andijan/@40.7729925,72.3361575,106m/data=!3m1!1e3!4m5!3m4!1s0x38bced78f61d2223:0xe9695b4df3a4348d!8m2!3d40.773079!4d72.3361251!5m1!1e4">
								<h3 class="mb-0 mt-0">Manzil</h3>
								<p class="mb-0">Andijon(ko'rish uchun bosing)</p>
							</a>
                        </div>
                    </div>
                </div>

            </div>

            <div class="spacer" data-height="50"></div>

            <!-- section header -->
            <div class="section-header">
                <h3 class="section-title">O'zimiz siz bilan bog'lanamiz</h3>
                <img src="/static/images/wave.svg" class="wave" alt="wave" />
				<div class="messages_pro"></div>
            </div>

            <!-- Contact Form -->
            <form id="contact-form" class="contact-form" method="POST">
                {% csrf_token %}
                <div class="messages"></div>
                
                <div class="row">
                    <div class="column col-md-6">
                        <!-- Name input -->
                        <div class="form-group">
                            <input type="text" class="form-control" id="InputName" placeholder="Ism" required="required" data-error="Name is required.">
                            <div class="help-block with-errors"></div>
                        </div>
                    </div>
                    
                    <div class="column col-md-6">
                        <!-- Email input -->
                        <div class="form-group">
                            <input type="text" class="form-control" id="InputSurname" placeholder="Familiya" required="required" data-error="Surname is required.">
                            <div class="help-block with-errors"></div>
                        </div>
                    </div>

                    <div class="column col-md-12">
                        <!-- Email input -->
                        <div class="form-group">
                            <input type="number" class="form-control" id="InputPhone" placeholder="Telefon (Davlat kodisiz)" required="required" data-error="Email is required.">
                            <div class="help-block with-errors"></div>
                        </div>
                    </div>
                </div>

                <a id="submit" class="btn btn-default">So'rovni yuborish</a><!-- Send Button -->

            </form>
            <!-- Contact Form end -->
		</div>
	</section>
	<!-- instagram feed -->
	<div class="instagram">
		<div class="container-xl">
			<!-- button -->
			<a href="#" class="btn btn-default btn-instagram">STEM suratlari</a>
			<!-- images -->
			<div class="instagram-feed d-flex flex-wrap">
				<div class="insta-item col-sm-2 col-6 col-md-2">
					<a href="#">
						<img src="/static/images/insta/insta-1.jpg" alt="insta-title" />
					</a>
				</div>
				<div class="insta-item col-sm-2 col-6 col-md-2">
					<a href="#">
						<img src="/static/images/insta/insta-2.jpg" alt="insta-title" />
					</a>
				</div>
				<div class="insta-item col-sm-2 col-6 col-md-2">
					<a href="#">
						<img src="/static/images/insta/insta-3.jpg" alt="insta-title" />
					</a>
				</div>
				<div class="insta-item col-sm-2 col-6 col-md-2">
					<a href="#">
						<img src="/static/images/insta/insta-4.jpg" alt="insta-title" />
					</a>
				</div>
				<div class="insta-item col-sm-2 col-6 col-md-2">
					<a href="#">
						<img src="/static/images/insta/insta-5.jpg" alt="insta-title" />
					</a>
				</div>
				<div class="insta-item col-sm-2 col-6 col-md-2">
					<a href="#">
						<img src="/static/images/insta/insta-6.jpg" alt="insta-title" />
					</a>
				</div>
			</div>
		</div>
	</div>

	<!-- footer -->
	<footer>
		<div class="container-xl">
			<div class="footer-inner">
				<div class="row d-flex align-items-center gy-4">
					<!-- copyright text -->
					<div class="col-md-4">
						<span class="copyright">© 2022 STEM School. Created by <a href="https://t.me/bdulhamid">Abdulhamid</a></span>
					</div>

					<!-- social icons -->
					<div class="col-md-4 text-center">
						<ul class="social-icons list-unstyled list-inline mb-0">
							<li class="list-inline-item"><a href="#"><i class="fab fa-telegram-plane"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="fab fa-youtube"></i></a></li>
						</ul>
					</div>

					<!-- go to top button -->
					<div class="col-md-4">
						<a href="#" id="return-to-top" class="float-md-end"><i class="icon-arrow-up"></i>Tepaga</a>
					</div>
				</div>
			</div>
		</div>
	</footer>

</div><!-- end site wrapper -->

<!-- search popup area -->
<div class="search-popup">
	<!-- close button -->
	<button type="button" class="btn-close" aria-label="Close"></button>
	<!-- content -->
	<div class="search-content">
		<div class="text-center">
			<h3 class="mb-4 mt-0">QIDIRISH...</h3>
		</div>
		<!-- form -->
		<form class="d-flex search-form">
			<input class="form-control me-2" type="search" placeholder="Nimani o'yladingiz?" aria-label="Search">
			<button class="btn btn-default btn-lg" type="submit"><i class="icon-magnifier"></i></button>
		</form>
	</div>
</div>

<!-- canvas menu -->
<div class="canvas-menu d-flex align-items-end flex-column">
	<!-- close button -->
	<button type="button" class="btn-close" aria-label="Close"></button>

	<!-- logo -->
	<div class="logo">
		<img src="/static/images/stem.jpg" alt="Katen" />
	</div>

	<!-- menu -->
	<nav>
		<ul class="vertical-menu">
			<li class="active">
				<a href="/">Bosh sahifa</a>
			</li>
			<li><a href="/elonlar/">E'lonlar</a></li>
			<li><a href="/yangiliklar/">Yangiliklar</a></li>
			<li>
				<a href="/jamoa/">Jamoamiz</a>
			</li>
			<li class='active'><a href="/jamoa/boglanish">Bog'lanish</a></li>
		</ul>
	</nav>

	<!-- social icons -->
	<ul class="social-icons list-unstyled list-inline mb-0 mt-auto w-100">
		<li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
		<li class="list-inline-item"><a href="#"><i class="fab fa-telegram"></i></a></li>
		<li class="list-inline-item"><a href="#"><i class="fab fa-youtube"></i></a></li>
	</ul>
</div>

<!-- JAVA SCRIPTS -->
<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/popper.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/slick.min.js"></script>
<script src="/static/js/jquery.sticky-sidebar.min.js"></script>
<script src="/static/js/custom.js"></script>
<script src="/static/js/ajax_response.js"></script>
<style>
	.avatar{
		width: 40px;
		height: 40px;
		margin-right: 10px;
		margin-top: 10px;
		border-radius: 50%;
	}
</style>
</body>
</html>